/**
 * @file top.v
 * 
 * This module implements all the modules of the RISC-V processor,
 * connecting the instruction memory, and data memory with the riscv_cpu module.
 * Also, it has a simple clock divider logic, to see the output of the cpu logic in 1Hz,
 * instead of the standard 100MHz generated by the FPGA.
 *
 * @input clk_in          Inputs clock signal.
 * @input reset           Inputs reset signal.
 * 
*/

module top (
    input clk, reset);
//! wire lines from other modules
wire [7:0] led;
wire [31:0] PC;
assign ProgramCounter = PC;
wire [31:0] Instr;
wire MemWrite_rv32;
wire [31:0] DataAdr_rv32, WriteData_rv32;
wire [31:0] ReadData;

//! instantiate processor and memories
riscv_cpu rvsingle (clk, reset, PC, Instr, MemWrite_rv32, DataAdr_rv32, WriteData_rv32, ReadData);
instr_mem imem (PC, Instr);
data_mem dmem (clk, MemWrite_rv32, DataAdr_rv32, WriteData_rv32, ReadData);

endmodule
